# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/article-llvm-rpg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/article-llvm-rpg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/article-llvm-rpg/CMakeFiles /workspaces/article-llvm-rpg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/article-llvm-rpg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rpg

# Build rule for target.
rpg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpg
.PHONY : rpg

# fast build rule for target.
rpg/fast:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/build
.PHONY : rpg/fast

src/generated/RpgLexer.o: src/generated/RpgLexer.cpp.o

.PHONY : src/generated/RpgLexer.o

# target to build an object file
src/generated/RpgLexer.cpp.o:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/generated/RpgLexer.cpp.o
.PHONY : src/generated/RpgLexer.cpp.o

src/generated/RpgLexer.i: src/generated/RpgLexer.cpp.i

.PHONY : src/generated/RpgLexer.i

# target to preprocess a source file
src/generated/RpgLexer.cpp.i:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/generated/RpgLexer.cpp.i
.PHONY : src/generated/RpgLexer.cpp.i

src/generated/RpgLexer.s: src/generated/RpgLexer.cpp.s

.PHONY : src/generated/RpgLexer.s

# target to generate assembly for a file
src/generated/RpgLexer.cpp.s:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/generated/RpgLexer.cpp.s
.PHONY : src/generated/RpgLexer.cpp.s

src/generated/RpgParser.o: src/generated/RpgParser.cpp.o

.PHONY : src/generated/RpgParser.o

# target to build an object file
src/generated/RpgParser.cpp.o:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/generated/RpgParser.cpp.o
.PHONY : src/generated/RpgParser.cpp.o

src/generated/RpgParser.i: src/generated/RpgParser.cpp.i

.PHONY : src/generated/RpgParser.i

# target to preprocess a source file
src/generated/RpgParser.cpp.i:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/generated/RpgParser.cpp.i
.PHONY : src/generated/RpgParser.cpp.i

src/generated/RpgParser.s: src/generated/RpgParser.cpp.s

.PHONY : src/generated/RpgParser.s

# target to generate assembly for a file
src/generated/RpgParser.cpp.s:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/generated/RpgParser.cpp.s
.PHONY : src/generated/RpgParser.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/rpg/compiler.o: src/rpg/compiler.cpp.o

.PHONY : src/rpg/compiler.o

# target to build an object file
src/rpg/compiler.cpp.o:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/compiler.cpp.o
.PHONY : src/rpg/compiler.cpp.o

src/rpg/compiler.i: src/rpg/compiler.cpp.i

.PHONY : src/rpg/compiler.i

# target to preprocess a source file
src/rpg/compiler.cpp.i:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/compiler.cpp.i
.PHONY : src/rpg/compiler.cpp.i

src/rpg/compiler.s: src/rpg/compiler.cpp.s

.PHONY : src/rpg/compiler.s

# target to generate assembly for a file
src/rpg/compiler.cpp.s:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/compiler.cpp.s
.PHONY : src/rpg/compiler.cpp.s

src/rpg/declaration.o: src/rpg/declaration.cpp.o

.PHONY : src/rpg/declaration.o

# target to build an object file
src/rpg/declaration.cpp.o:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/declaration.cpp.o
.PHONY : src/rpg/declaration.cpp.o

src/rpg/declaration.i: src/rpg/declaration.cpp.i

.PHONY : src/rpg/declaration.i

# target to preprocess a source file
src/rpg/declaration.cpp.i:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/declaration.cpp.i
.PHONY : src/rpg/declaration.cpp.i

src/rpg/declaration.s: src/rpg/declaration.cpp.s

.PHONY : src/rpg/declaration.s

# target to generate assembly for a file
src/rpg/declaration.cpp.s:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/declaration.cpp.s
.PHONY : src/rpg/declaration.cpp.s

src/rpg/generator.o: src/rpg/generator.cpp.o

.PHONY : src/rpg/generator.o

# target to build an object file
src/rpg/generator.cpp.o:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/generator.cpp.o
.PHONY : src/rpg/generator.cpp.o

src/rpg/generator.i: src/rpg/generator.cpp.i

.PHONY : src/rpg/generator.i

# target to preprocess a source file
src/rpg/generator.cpp.i:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/generator.cpp.i
.PHONY : src/rpg/generator.cpp.i

src/rpg/generator.s: src/rpg/generator.cpp.s

.PHONY : src/rpg/generator.s

# target to generate assembly for a file
src/rpg/generator.cpp.s:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/generator.cpp.s
.PHONY : src/rpg/generator.cpp.s

src/rpg/parser.o: src/rpg/parser.cpp.o

.PHONY : src/rpg/parser.o

# target to build an object file
src/rpg/parser.cpp.o:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/parser.cpp.o
.PHONY : src/rpg/parser.cpp.o

src/rpg/parser.i: src/rpg/parser.cpp.i

.PHONY : src/rpg/parser.i

# target to preprocess a source file
src/rpg/parser.cpp.i:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/parser.cpp.i
.PHONY : src/rpg/parser.cpp.i

src/rpg/parser.s: src/rpg/parser.cpp.s

.PHONY : src/rpg/parser.s

# target to generate assembly for a file
src/rpg/parser.cpp.s:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/parser.cpp.s
.PHONY : src/rpg/parser.cpp.s

src/rpg/symtab.o: src/rpg/symtab.cpp.o

.PHONY : src/rpg/symtab.o

# target to build an object file
src/rpg/symtab.cpp.o:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/symtab.cpp.o
.PHONY : src/rpg/symtab.cpp.o

src/rpg/symtab.i: src/rpg/symtab.cpp.i

.PHONY : src/rpg/symtab.i

# target to preprocess a source file
src/rpg/symtab.cpp.i:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/symtab.cpp.i
.PHONY : src/rpg/symtab.cpp.i

src/rpg/symtab.s: src/rpg/symtab.cpp.s

.PHONY : src/rpg/symtab.s

# target to generate assembly for a file
src/rpg/symtab.cpp.s:
	$(MAKE) -f CMakeFiles/rpg.dir/build.make CMakeFiles/rpg.dir/src/rpg/symtab.cpp.s
.PHONY : src/rpg/symtab.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... rpg"
	@echo "... src/generated/RpgLexer.o"
	@echo "... src/generated/RpgLexer.i"
	@echo "... src/generated/RpgLexer.s"
	@echo "... src/generated/RpgParser.o"
	@echo "... src/generated/RpgParser.i"
	@echo "... src/generated/RpgParser.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/rpg/compiler.o"
	@echo "... src/rpg/compiler.i"
	@echo "... src/rpg/compiler.s"
	@echo "... src/rpg/declaration.o"
	@echo "... src/rpg/declaration.i"
	@echo "... src/rpg/declaration.s"
	@echo "... src/rpg/generator.o"
	@echo "... src/rpg/generator.i"
	@echo "... src/rpg/generator.s"
	@echo "... src/rpg/parser.o"
	@echo "... src/rpg/parser.i"
	@echo "... src/rpg/parser.s"
	@echo "... src/rpg/symtab.o"
	@echo "... src/rpg/symtab.i"
	@echo "... src/rpg/symtab.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

